version: '3.8'
services:
  app:
    container_name: api
    build: .
    command: "flask run --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - "db"
  db:
    container_name: db
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=Test
    ports:
      - 27017:27017
    networks:
      - backend
    
networks:
  backend: